services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Authentication\:
        resource: '../../../../src/lib/Authentication/*'

    Ibexa\PersonalizationClient\Authentication\ExportAuthenticator:
        arguments:
            $credentialsResolver: '@Ibexa\PersonalizationClient\Config\ExportCredentialsResolver'
