services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Client\:
        resource: '../../../../src/lib/Client/*'

    GuzzleHttp\Client: ~

    GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'

    Ibexa\PersonalizationClient\Client\EzRecommendationClient:
        arguments:
            $credentialsResolver: '@Ibexa\PersonalizationClient\Config\EzRecommendationClientCredentialsResolver'
