services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ibexa\Bundle\PersonalizationClient\Controller\:
        resource: '../../../Controller/*'

    Ibexa\Bundle\PersonalizationClient\Controller\RecommendationController:
        public: true
        arguments:
            $credentialsResolver: '@Ibexa\PersonalizationClient\Config\EzRecommendationClientCredentialsResolver'

    ez_recommendation:
        alias: Ibexa\Bundle\PersonalizationClient\Controller\RecommendationController
        public: true

    Ibexa\Bundle\PersonalizationClient\Controller\ContentController:
        arguments:
            $authenticator: '@Ibexa\PersonalizationClient\Authentication\ExportAuthenticator'

    Ibexa\Bundle\PersonalizationClient\Controller\ContentTypeController:
        arguments:
            $authenticator: '@Ibexa\PersonalizationClient\Authentication\ExportAuthenticator'

    Ibexa\Bundle\PersonalizationClient\Controller\ExportController:
        arguments:
            $authenticator: '@Ibexa\PersonalizationClient\Authentication\ExportAuthenticator'
        tags:
            - { name: monolog.logger, channel: ezrecommendation }
