services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ibexa\Bundle\PersonalizationClient\ParamConverter\:
        resource: '../../../../src/bundle/ParamConverter/*'

    Ibexa\Bundle\PersonalizationClient\ParamConverter\ListParamConverter:
        tags:
            - { name: request.param_converter, priority: -2, converter: list_converter }

    Ibexa\Bundle\PersonalizationClient\ParamConverter\ExportRequestParamConverter:
        tags:
            - { name: request.param_converter, priority: 2, converter: export_request_converter }
