services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Event\:
        resource: '../../../../src/lib/Event/*'

    Ibexa\PersonalizationClient\Event\Listener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, priority: 255 }
            - { name: monolog.logger, channel: ezrecommendation }

    Ibexa\PersonalizationClient\Service\NotificationService: '@Ibexa\PersonalizationClient\Service\EventNotificationService'
