services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Exporter\:
        resource: '../../../../src/lib/Exporter/*'

    Ibexa\PersonalizationClient\Exporter\Exporter:
        arguments:
            $repository: '@ezpublish.api.repository'
        tags:
            - { name: monolog.logger, channel: ezrecommendation }
