services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Factory\EzRecommendationClientAPIFactory: ~

    Ibexa\PersonalizationClient\Factory\FakeRequestFactory: ~

    Ibexa\PersonalizationClient\Factory\RequestFactoryInterface:
        '@Ibexa\PersonalizationClient\Factory\FakeRequestFactory'

    Ibexa\PersonalizationClient\Factory\TokenFactory: ~

    Ibexa\PersonalizationClient\Factory\TokenFactoryInterface:
        '@Ibexa\PersonalizationClient\Factory\TokenFactory'

    Ibexa\PersonalizationClient\Factory\Export\ParametersFactory:
        arguments:
            $siteAccessService: '@ezpublish.siteaccess_service'
            $credentialsResolver: '@Ibexa\PersonalizationClient\Config\EzRecommendationClientCredentialsResolver'

    Ibexa\PersonalizationClient\Factory\Export\ParametersFactoryInterface:
        '@Ibexa\PersonalizationClient\Factory\Export\ParametersFactory'
