services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Field\:
        resource: '../../../../src/lib/Field/*'

    Ibexa\PersonalizationClient\Field\Value:
        arguments:
            $parameters: {fieldIdentifiers: "%ezrecommendation.default.field.identifiers%"}
        tags:
            - { name: monolog.logger, channel: ezrecommendation }

    Ibexa\PersonalizationClient\Field\TypeValue:
        arguments:
            $richHtml5Converter: '@ezrichtext.converter.output.xhtml5'
