services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\File\FileManager:
        $exportDocumentRoot: '%ezrecommendation.default.export.document_root%'

    Ibexa\PersonalizationClient\File\FileManagerInterface:
        '@Ibexa\PersonalizationClient\File\FileManager'
