services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Helper\:
        resource: '../../../../src/lib/Helper/*'

    Ibexa\PersonalizationClient\Helper\SiteAccessHelper:
        arguments:
            $siteAccessConfig: '%ezrecommendation.siteaccess_config%'
            $defaultSiteAccessName: '%ezpublish.siteaccess.default%'

    Ibexa\PersonalizationClient\Helper\ExportProcessRunnerHelper:
        arguments:
            $kernelEnvironment: '%kernel.environment%'
        tags:
            - { name: monolog.logger, channel: ezrecommendation }

    Ibexa\PersonalizationClient\Helper\ImageHelper:
        arguments:
            $imageVariationService: '@ezpublish.fieldType.ezimage.variation_service'
