services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Mapper\:
        resource: '../../../../src/lib/Mapper/*'

    Ibexa\PersonalizationClient\Mapper\RelationMapper:
        arguments:
            $fieldMappings: "%ezrecommendation.default.field.relations%"
