services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Response\ItemListResponse:
        tags:
            - { name: ibexa.personalization.rest.response_type, type: http }

    Ibexa\PersonalizationClient\Response\ResponseInterface:
        '@Ibexa\PersonalizationClient\Response\ItemListResponse'
