services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Service\ExportService:
        arguments:
            $credentialsResolver: '@Ibexa\PersonalizationClient\Config\ExportCredentialsResolver'
            $notificationService: '@Ibexa\PersonalizationClient\Service\ExportNotificationService'

    Ibexa\PersonalizationClient\Service\ExportServiceInterface:
        '@Ibexa\PersonalizationClient\Service\ExportService'

    Ibexa\PersonalizationClient\Service\ExportNotificationService: ~

    Ibexa\PersonalizationClient\Service\ContentService:
        arguments:
            $defaultAuthorId: '%ezrecommendation.default.author_id%'
            $defaultSiteAccess: '%ezpublish.siteaccess.default%'

    Ibexa\PersonalizationClient\Service\ContentServiceInterface:
        '@Ibexa\PersonalizationClient\Service\ContentService'

    Ibexa\PersonalizationClient\Service\RecommendationService: ~

    Ibexa\PersonalizationClient\Service\RecommendationServiceInterface:
        '@Ibexa\PersonalizationClient\Service\RecommendationService'

    Ibexa\PersonalizationClient\Service\UserService: ~

    Ibexa\PersonalizationClient\Service\UserServiceInterface:
        '@Ibexa\PersonalizationClient\Service\UserService'

    Ibexa\PersonalizationClient\Service\EventNotificationService:
        arguments:
            $clientCredentials: '@Ibexa\PersonalizationClient\Config\EzRecommendationClientCredentialsResolver'
            $exportCredentials: '@Ibexa\PersonalizationClient\Config\ExportCredentialsResolver'

    Ibexa\PersonalizationClient\Service\Storage\DataSourceService:
        arguments:
            $sources: !tagged_iterator ibexa.personalization.data_source

    Ibexa\PersonalizationClient\Service\Storage\DataSourceServiceInterface:
        '@Ibexa\PersonalizationClient\Service\Storage\DataSourceService'
