services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Ibexa\PersonalizationClient\Strategy\Storage\GroupItemStrategyInterface:
            tags:
                - { name: ibexa.personalization.group_item.strategy }

    Ibexa\PersonalizationClient\Strategy\Storage\GroupByItemTypeAndLanguageStrategy: ~

    Ibexa\PersonalizationClient\Strategy\Storage\GroupItemStrategyDispatcher:
        arguments:
            $groupItemStrategies: !tagged_iterator
                tag: ibexa.personalization.group_item.strategy
                default_index_method: getIndex
                index_by: key

    Ibexa\PersonalizationClient\Strategy\Storage\GroupItemStrategyDispatcherInterface:
        '@Ibexa\PersonalizationClient\Strategy\Storage\GroupItemStrategyDispatcher'
