services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ibexa\Bundle\PersonalizationClient\Templating\:
        resource: '../../../Templating/*'

    Ibexa\Bundle\PersonalizationClient\Templating\Twig\Functions\Recommendation:
        public: true
        arguments:
            $credentialsResolver: '@Ibexa\PersonalizationClient\Config\EzRecommendationClientCredentialsResolver'
