services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\PersonalizationClient\Value\ContentDataVisitor:
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Ibexa\PersonalizationClient\Value\ContentData }
